// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace DataBaseHelperSQLite.Data.Models
{

    /// <summary>
    /// Модель BibliographicMaterial
    /// </summary>
    public partial class BibliographicMaterial
    {

        /// <summary>
        /// ID
        /// </summary>
        public int? Id { get; set; }

        /// <summary>
        /// Название
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Год издания
        /// </summary>
        public string Date { get; set; }

        /// <summary>
        /// Картинка
        /// </summary>
        public string Img { get; set; }

        /// <summary>
        /// ID автора
        /// </summary>
        public int? AuthorId { get; set; }

        /// <summary>
        /// ID издательства
        /// </summary>
        public int? PublisherId { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Author Author { get; set; }
        [JsonIgnore]
        [IgnoreDataMember]
        public virtual Publisher Publisher { get; set; }
    }
}